### ISSUE TITLE
Purpose of inverse softplus and square root of GP/TP variance?

### ISSUE THREAD

**Issue by christabella** [IraKorshunova/bruno#3]
Why is the trainable variable of the variance of the GP/TP kernel (`v` in Eq. 9 of the BRUNO paper, diagonal values on the kernel matrix) expressed as the inverse softplus of the square root of the actual variance?

https://github.com/IraKorshunova/bruno/blob/d185d4bebd9513506f6437702a43d1a55badb697/nn_extra_gauss.py#L35

And then actual variance is recovered like this:
https://github.com/IraKorshunova/bruno/blob/d185d4bebd9513506f6437702a43d1a55badb697/nn_extra_gauss.py#L37

Is it simply to ensure `v` is non-negative? But then taking the square of `self.var_vbl` would suffice for that. Is the softplus some kind of trick for stability or convergence (and if so is it documented anywhere)? Thank you!

P.S. What does the `m1` in `m1_shapenet` stand for? 🤔

**Comment by IraKorshunova** [comment]
Other parameterisations exist, but I wanted var_vbl to be a standard deviation and using softplus when learning std seems common.  
m1 stands for model 1 :)

**Comment by christabella** [comment]
Thanks so much for demystifying! I guess softplus is a good choice since it's a bijective, monotonic transformation etc and positive but it shouldn't matter too much...
