### ISSUE TITLE
Drawbacks of conditional BRUNO compared to RNN BRUNO (not a bug)

### ISSUE THREAD

**Issue by christabella** [IraKorshunova/bruno#4]
Hello, thank you for open-sourcing the code! I have a few high-level questions about the models:
## 1. Why is validation only done for RNN and not conditional?

In the original RNN version, there is validation done during training:
https://github.com/IraKorshunova/bruno/blob/c631d3d6d7189f23956ee428b4f0ebf467272d2a/config_rnn/train.py#L201-L208

Whereas in the conditional version, `eval_loss` is never used:
https://github.com/IraKorshunova/bruno/blob/c631d3d6d7189f23956ee428b4f0ebf467272d2a/config_conditional/train.py#L79-L84

## 2. Is conditional BRUNO not maximizing joint (conditional) log likelihood?

BRUNO is clearly maximizing the **joint log likelihood**:
![image](https://user-images.githubusercontent.com/2038751/72356118-5e940a80-36f1-11ea-8c2b-b9deaf78c645.png)

However, conditional BRUNO does not seem to be maximizing the **joint conditional log likelihood**... or is it? 
![image](https://user-images.githubusercontent.com/2038751/72355861-df063b80-36f0-11ea-953e-a306185f05f9.png)

## 3. "Conditional de Finetti" is not guaranteed
Do you think this is this a problem, or not really since in practice it works nonetheless?

Thank you very much!

**Comment by IraKorshunova** [comment]
Hello! Thank you for the questions!
Q1: the conditional code was hastily written, so it might be missing some pieces. I also didn't look much at the validation scores as far as I remember. 
Q2: I think it does maximize the conditional joint log-likelihood.
Q3: From a theory point of view, it's probably unsatisfactory that there is no proof. I would be happier if there was one. Though, if the goal is to make a working model like with all deep learning, then I guess it's fine.
